server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: ENC(aGn4MyWoNQH8UyOCYY+RYA==)
    password: ENC(aGn4MyWoNQH8UyOCYY+RYA==)

# 日志级别
logging:
  level:
    root: WARN
    com.nixum.mainWebService: WARN